version: '3.9'

services:
  api_db:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: api-golang
    volumes:
        - ./db_dump:/docker-entrypoint-initdb.d
    ports:
        - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080